### ISSUE TITLE
[Issue] AutomaticInventoryFixPlugin (the log u need me provided before)

### ISSUE THREAD

**Issue by CoolLKKPS** [Test-Account666/LethalCompany-TestAccountFixes#1]
[LogOutput.txt](https://github.com/user-attachments/files/15737650/LogOutput.txt)
i still can't get any useful spiderfix mod log, but i did forgot to turn off "lesslog" mod, maybe nxt time

**Comment by Test-Account666** [comment]
You might want to enable the debug log for the inventory fix to provide me with more information.

Also, set the log level to `Verbose`

**Comment by CoolLKKPS** [comment]
ok

**Comment by CoolLKKPS** [comment]
@Test-Account666 well i thought that will be hard to reproduce, but well here's the log
[LogOutput.txt](https://github.com/user-attachments/files/15738854/LogOutput.txt)

**Comment by CoolLKKPS** [comment]
3 items, only pill item saved, and after that the glitch will correctly fixed (include speed glitch)

**Comment by Test-Account666** [comment]
That's just wonderful:
![grafik](https://github.com/Test-Account666/LethalCompany-TestAccountFixes/assets/36412486/c671ccc1-a67c-4ff2-8c8c-eef77be04ed4)


I'll have a look it it.

Thanks for the report

**Comment by CoolLKKPS** [comment]
nice, but btw
spider damage *fix* tbh, spider are already easy to deal with, if u *fix* it, even this is not a necessary *fix*, but still u need to make sure everyone takes the same spider damage, tbh a bit worry this can be ***use*** for some people who just like to use tool to win

**Comment by CoolLKKPS** [comment]
this issue still not fix in the newest version

**Comment by CoolLKKPS** [comment]
@Test-Account666 a mention, this fix feature no longer work
